version: '3'
services:
  server:
    build: ./
    environment:
      MONGO_ADDR: "db"
    depends_on:
      - db
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:f2e-mid.gmin.tk"
      - "traefik.port=8080"
  db:
    image: "mvertes/alpine-mongo"
    restart: always
    volumes:
      - db-data:/data/db
volumes:
  db-data: